# Generated by Django 5.2.4 on 2025-07-14 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('biography', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField(blank=True, help_text='Fecha de lanzamiento (YYYY-MM-DD)', null=True)),
                ('format', models.CharField(choices=[('VINYL', 'Vinilo'), ('CD', 'CD'), ('DIGITAL', 'Digital')], default='VINYL', max_length=10)),
                ('catalog_number', models.CharField(blank=True, max_length=100, null=True)),
                ('condition', models.CharField(blank=True, help_text='Ej: VG+, NM, Mint', max_length=50, null=True)),
                ('location', models.CharField(blank=True, help_text='Ej: Estante 3, Caja de CDs', max_length=255, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.artist')),
            ],
            options={
                'unique_together': {('title', 'artist', 'release_date')},
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('track_number', models.IntegerField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album')),
            ],
            options={
                'ordering': ['track_number'],
                'unique_together': {('album', 'track_number')},
            },
        ),
    ]
